# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync_repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.in2p3.fr >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure git user
        run: |
          git config --global user.name "Romuald MARIN"
          git config --global user.email "romuald.marin@france-bioinformatique.fr"
          git clone git@gitlab.in2p3.fr:ifb-biosphere/wp4-mudis4ls/slides_ai_dna.git
      - name: Merge and Resolve Conflicts
        run: |
          cd slides_ai_dna
          git merge slides_AI_DNA/main --allow-unrelated-histories || true
          # Automatically resolve conflicts by keeping the changes from GitHub
          git checkout --ours README.md
          git add README.md
          git commit -m "Resolved merge conflicts automatically"

      - name: Push Changes Back to GitLab
        run: |
          cd slides_ai_dna
          git push origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

